### ISSUE TITLE
FYI: alternative option: design first

### ISSUE THREAD

**Issue by seriousme** [siegfriedgrimbeek/fastify-api#1]
Hi,

nice writeup on freecodecamp. Somehow I couldn't comment there so thats why I mention this here:

An alternative option to runtime generation of the swagger file is to create the swaggerfile (or openapi-spec ;-)) first and then use: https://github.com/seriousme/fastify-openapi-glue

This will save you from having to manually create routes as well.

Cheers,
Hans

**Comment by siegfriedgrimbeek** [comment]
Awesome! Thanks a lot Hans, I will check it out and I might use it for the next tut!
