### ISSUE TITLE
Not loading on a Docker or a VM

### ISSUE THREAD

**Issue by red1** [siegfriedgrimbeek/fastify-api#5]
On this line 
https://github.com/siegfriedgrimbeek/fastify-api/blob/7a906ba310d1c68159d1c07458b0419f3f0bfe22/src/index.js#L31
Please change
`await fastify.listen(3000)`
to 
`await fastify.listen(3000, '0.0.0.0')`
A PR is sent for merge
#6

**Comment by siegfriedgrimbeek** [comment]
Merged the pull request, thanks!
