### ISSUE TITLE
Windows 10 install

### ISSUE THREAD

**Issue by johntom** [siegfriedgrimbeek/fastify-api#7]
Just read your article on medium and decided to give it a try as I'm looking to port some sails/trails legacy apps.
windows 10
node 10.15.0
npm 6.4,1
1) npm start failed until I changed
 "start": "nodemon ./src/index.js",
2) console reports Mongodb connected... yet 
http://localhost:3000/ displays
{
statusCode: 404,
error: "Not Found",
message: "Not Found"
}
2) after posting a record with postman 
http://localhost:3000/api/cars
displays
[
{
_id: "5cb4c6c5f2169e448030ae9d",
title: "Z3",
brand: "BMW",
price: "7000",
age: 10,
services: {
BMW Hong Kong: "01/01/2001",
BMW NY: "5/5/2015"
},
__v: 0
}
]
3) Seems like its working but not sure why I get a  404 
4) Swagger does not use port 3000 so no data is retuned by get

If I get traction with this framwork I will add to your foundation with JWT, muter and other options. Also looking for a place to store mutiple databases and then have models use attach to the correct database.

**Comment by siegfriedgrimbeek** [comment]
Hi,

1. I recently ran into the same issue, I am not sure whether this was a change with nodemon but it is solved as per your solution.

2. There is no default route setup, hence the 404, but you can easily do this as follows:

```
{
    method: 'GET',
    url: '/',
    handler: async function (req, reply) {
      reply.send({ hello: 'world' })
    }
}
```
3 - 4. Yes only those routes are setup.

5. Not sure what you mean?

Regarding the multiple databases, I am working on part two of this, where we will get rid of Mongoose and use the native MongoDB driver, which easily allows for multiple databases.

Hope this helps!
